# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_messages.Card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_messages.Card'),
        ),
    ]
