# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_messages', '0002_auto_20171001_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='question_text',
            new_name='card_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
